version: 0.0
os: linux
files:
   - source: /
     destination: /home/ec2-user/app/
permissions:
   - object: /home/ec2-user/app
     pattern: "**"
     owner: ec2-user
     mode: 755
hooks:
   BeforeInstall:
    - location: scripts/killapp.sh
      runas: ec2-user
   AfterInstall:
    - location: scripts/startapp.sh
      runas: ec2-user
